<?php

namespace AppBundle\Repository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPlayersFromGame($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('p')
           ->from('\AppBundle\Entity\Player', 'p')
           ->join('p.games', 'g')
           ->where($qb->expr()->eq('g.id', $id));

        return $qb->getQuery()->getResult();
    }
}
