# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #app.parameter: value

services:
    app.file_uploader:
        class: AppBundle\FileUploader
        #arguments: ["%parameter_name%"]
